### ISSUE TITLE
Upgrade davical to 1.1.7

### ISSUE THREAD

**Issue by jfjallid** [janLo/dockerfiles#5]
I noticed that the davical setup fails now using your latest container running davical 1.1.5 together with latest postgres which is version 10.3. I believe atleast davical version 1.1.6 is required to work with postgres 10.x.

**Comment by janLo** [comment]
t think the easiest way to achieve ihis is to switch to a more recent debian base image, as davical is installed from the debian repo.
I don't use davical anymore (finally nextcloud got me ;) ) but I can merge a PR if you want to do the update.
